import { deflateSync } from "node:zlib";

// 1x1 transparent PNG
export const PNG_1PX = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "base64"
);

// Shape of a PrusaSlicer 2.x ASCII export for an MK4S (abridged).
export function asciiGcode() {
  const thumb = PNG_1PX.toString("base64");
  return [
    "; generated by PrusaSlicer 2.9.2 on 2026-10-01 at 18:00:00 UTC",
    "",
    "; ",
    "; thumbnail begin 16x16 " + thumb.length,
    "; " + thumb,
    "; thumbnail end",
    "; ",
    "; thumbnail_QOI begin 220x124 8",
    "; cW9pZgAA",
    "; thumbnail_QOI end",
    "",
    "M17 ; enable steppers",
    "M555 X91.5 Y83.2 W67 H43.6",
    "G28 ; home",
    "G1 X10 Y10 Z0.2 E1 F1500",
    "G1 X20 Y20 E2",
    "",
    "; filament used [mm] = 4321.10",
    "; filament used [cm3] = 10.39",
    "; filament used [g] = 12.88",
    "; filament cost = 0.32",
    "; estimated printing time (normal mode) = 1h 23m 45s",
    "; estimated printing time (silent mode) = 1h 30m 2s",
    "; max_layer_z = 18.2",
    "",
    "; prusaslicer_config = begin",
    "; filament_type = PETG",
    "; layer_height = 0.2",
    "; printer_model = MK4S",
    "; prusaslicer_config = end",
    "",
  ].join("\n");
}

function block(type: number, params: Buffer, data: Buffer, compress: boolean) {
  const payload = compress ? deflateSync(data) : data;
  const header = Buffer.alloc(compress ? 12 : 8);
  header.writeUInt16LE(type, 0);
  header.writeUInt16LE(compress ? 1 : 0, 2);
  header.writeUInt32LE(data.length, 4);
  if (compress) header.writeUInt32LE(payload.length, 8);
  const checksum = Buffer.alloc(4); // CRC32 slot; the parser skips it
  return Buffer.concat([header, params, payload, checksum]);
}

const encodingIni = () => Buffer.from([0, 0]);

export function binaryGcode() {
  const fileHeader = Buffer.alloc(10);
  fileHeader.write("GCDE", 0, "ascii");
  fileHeader.writeUInt32LE(1, 4);
  fileHeader.writeUInt16LE(1, 8); // CRC32 checksums

  const thumbParams = Buffer.alloc(6);
  thumbParams.writeUInt16LE(0, 0); // PNG
  thumbParams.writeUInt16LE(16, 2);
  thumbParams.writeUInt16LE(16, 4);

  return Buffer.concat([
    fileHeader,
    block(0, encodingIni(), Buffer.from("Producer=PrusaSlicer 2.9.2\n"), true),
    block(
      3,
      encodingIni(),
      Buffer.from("printer_model=MK4S\nfilament_type=PLA\nnozzle_diameter=0.4\n"),
      true
    ),
    block(5, thumbParams, PNG_1PX, false),
    block(
      4,
      encodingIni(),
      Buffer.from("filament used [g]=3.21\nestimated printing time (normal mode)=2d 1h 0m 5s\n"),
      true
    ),
    block(2, encodingIni(), Buffer.from("layer_height=0.2\n"), true),
    // A G-code block: the parser must stop here without decoding it.
    block(1, Buffer.from([1, 0]), Buffer.from("not really heatshrink"), false),
  ]);
}
